### ISSUE TITLE
Create Method GetAddress

### ISSUE THREAD

**Issue by SideswipeN7** [SideswipeN7/TAW-Magazyn#18]
story points 2
I want to *Create Method GetAddress*

As a *Developer*

So *We can get address data by ID*

AC:  *Method should take argument int ID and return object Address witch selected ID if ID is not in database should return null object if no one has that ID*

**Comment by SideswipeN7** [comment]
Method need to return also null object

**Comment by youkero** [comment]
When there is no Address object witch selected ID this method will return null
