### ISSUE TITLE
Create LoginController

### ISSUE THREAD

**Issue by SideswipeN7** [SideswipeN7/TAW-Magazyn#5]
story points 1
I want to *Create LoginController*

As a *Developer*

So *We can code methods for log in request*

AC:  *Created empty Controller*

**Comment by GrzegorzKatze** [comment]
Jeżeli zadanie jest w statusie QA, to wynik zadania tzn. Kod źródłowy, dokumenty, itd.. Powinny zostać umieszczone w branchu "develope". To z tej gałęzi testerzy pobierają wersje "niestabilne/stabilne" do testów. Tester(QA) nie testuje gałęzi programistów które zostały stworzone pod konkretne zadania. Ale główną gałaź dla aplikacji. Dlatego jeżeli coś jest w statusie "Done", a nie jest połączone do "develope" to nie może być w statusie "done".   Zadanie jest wykonane tylko i wyłącznie wtedy gdy:
1. Spełnia kryteria akceptacji
2. Kod "całej" aplikacji wrzucony na develope kompiluje się
3. Zmiany znajdują się w gałęzi develope
