### ISSUE TITLE
Create Methods for TDD

### ISSUE THREAD

**Issue by SideswipeN7** [SideswipeN7/TAW-Magazyn#72]
story points 2 for each method

I want to *Create Methods for TDD*

As a *Team Leader*

So We can *learn better TDD*

AC: *Each person must have write at least two methods for tessting. Please write in comment wich method are you testing*

**Comment by SideswipeN7** [comment]
GetCategories() test made

**Comment by stanustanley** [comment]
Login()

**Comment by michal81818** [comment]
GetTransItems()

**Comment by SideswipeN7** [comment]
GetItems()

**Comment by SideswipeN7** [comment]
ChangeItem(Artykul artykul)

**Comment by youkero** [comment]
GetAddress(int id), ChangeAddress(Adres adres), RegisterAddress(Adres adres), RegisterSupplier(Dostawca dostawca), ChangeSupplier(Dostawca dostawca), ChangeCategory(Kategoria kategoria)

**Comment by michal81818** [comment]
GetTransactions()

**Comment by michal81818** [comment]
GetTransItems()

**Comment by stanustanley** [comment]
GetSupplier(id) GetSuppliers(),

**Comment by SideswipeN7** [comment]
- SideswipeN7   6 ST
- stanustanley    6 ST
- michal81818   4 ST
- youkero         12 ST
